name: google_sign_in_mocks
description: Mocks for Google Sign In. Use this package with `firebase_auth_mocks` to write unit tests involving Firebase Authentication.
version: 0.2.0
homepage: http://blog.wafrat.com
repository: https://github.com/atn832/google_sign_in_mocks

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.0
  mockito: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.0.0
